numbers = [{'number': 'BR-112018005425', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'CN-118999932', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'GC-0005871', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'ID-2021', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'MX-333025', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'SG-10202400572', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'SG-11202106482', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'TH-2101003563', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'US-20240385316', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'US-20240395121', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'WO-2024242153', 'number_details': None, 'status': 'ERROR', 'status_reason': 'Not found'},
             {'number': 'JPWO2019216414', 'number_details': None, 'status': 'ERROR', 'status_reason': 'unknown patent number pattern'},
             {'number': 'JPWO2007046180', 'number_details': None, 'status': 'ERROR', 'status_reason': 'unknown patent number pattern'},
             {'number': 'IL-197306-A',
              'number_details': {'titles': [{'lang': 'HE', 'text': 'שיטה ומערכת להדמית אולטראסאונד מלאכותית'},
                                            {'lang': 'EN', 'text': 'Method and apparatus for ultrasound synthetic imaging'}],
                                 'ucid': 'IL-197306-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'CN-118333919-B',
              'number_details': {'titles': [{'lang': 'EN', 'text': 'Image enhancement method for ultrasonic imaging gas leakage detector'},
                                            {'lang': 'ZH', 'text': '一种用于超声波成像气体泄漏检测仪的图像增强方法'}],
                                 'ucid': 'CN-118333919-B'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'JP-2022502113-A',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': '3D ultrasound imaging with wide focused transmit beam at high display frame rate'},
                                            {'lang': 'JA', 'text': '高い表示フレームレートで幅広集束送信ビームを用いる３Ｄ超音波イメージング'}],
                                 'ucid': 'JP-2022502113-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'BR-112014013059-A2',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': 'method and system for performing acoustic imaging, and machine readable storage device'},
                                            {'lang': 'PT',
                                             'text': 'método e sistema para realizar formação de imagem acústica, e, dispositivo de armazenagem '
                                                     'legível por máquina'}],
                                 'ucid': 'BR-112014013059-A2'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'CN-118855449-A',
              'number_details': {'titles': [{'lang': 'ZH', 'text': '一种声学测井的声波远探测成像方法、设备、介质及产品'},
                                            {'lang': 'EN',
                                             'text': 'Acoustic far-detection imaging method, equipment, medium and product for acoustic logging'}],
                                 'ucid': 'CN-118855449-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'BR-112022013974-A2',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': 'APPARATUS AND METHOD FOR REPRODUCING A SPATIALLY EXTENDED SOUND SOURCE OR APPARATUS AND METHOD '
                                                     'FOR GENERATING A DESCRIPTION FOR A SPATIALLY EXTENDED SOUND SOURCE USING ANCHORING '
                                                     'INFORMATION'},
                                            {'lang': 'PT',
                                             'text': 'APARELHO E MÉTODO PARA REPRODUZIR UMA FONTE SONORA ESPA-CIALMENTE ESTENDIDA OU APARELHO E '
                                                     'MÉTODO PARA GERAR UMA DESCRIÇÃO PARA UMA FONTE SONORA ESPACIALMENTE ESTENDIDA COM O USO DE '
                                                     'INFORMAÇÕES DE ANCORAGEM'}],
                                 'ucid': 'BR-112022013974-A2'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'JP-2021522912-A',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': 'Ultrasound imaging with sparse sampling and related equipment, systems and methods'},
                                            {'lang': 'JA', 'text': '疎サンプリングによる超音波撮像ならびに関連する装置、システムおよび方法'}],
                                 'ucid': 'JP-2021522912-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'BR-112021011170-A2',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': 'Apparatus and method for reproducing a spatially extended sound source or apparatus and method '
                                                     'for generating a bit stream from a spatially extended sound source'},
                                            {'lang': 'PT',
                                             'text': 'Aparelho e método para reproduzir uma fonte sonora espacialmente estendida ou aparelho e '
                                                     'método para gerar um fluxo de bits a partir de uma fonte sonora espacialmente estendida'}],
                                 'ucid': 'BR-112021011170-A2'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'BR-112014013059-A8',
              'number_details': {'titles': [], 'ucid': 'BR-112014013059-A8'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'JP-2022515998-A',
              'number_details': {'titles': [{'lang': 'EN',
                                             'text': 'A device and method for playing a spatially expanded sound source, or a device and method for '
                                                     'generating a bitstream from a spatially expanded sound source.'},
                                            {'lang': 'JA', 'text': '空間的に拡張された音源を再生するための装置および方法、または、空間的に拡張された音源からビットストリームを生成するための装置および方法'}],
                                 'ucid': 'JP-2022515998-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'BR-112019002090-A2',
              'number_details': {'titles': [{'lang': 'PT',
                                             'text': 'reconhecimento de padrão de tempo real e interpretação automática de imagens de reflexão '
                                                     'acústica'},
                                            {'lang': 'EN',
                                             'text': 'real-time pattern recognition and automatic interpretation of acoustic reflection images'}],
                                 'ucid': 'BR-112019002090-A2'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'IL-197306-A0',
              'number_details': {'titles': [{'lang': 'EN', 'text': 'METHOD AND APPARATUS FOR ULTRASOUND SYNTHETIC IMAGING'}], 'ucid': 'IL-197306-A0'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'IL-197306-D0', 'number_details': {'titles': [], 'ucid': 'IL-197306-D0'}, 'status': 'OK', 'status_reason': 'success'},
             {'number': 'BR-112019002090-B1',
              'number_details': {'titles': [{'lang': 'PT',
                                             'text': 'MÉTODO PARA REALIZAR PERFILAGEM DE POÇO EM UM POÇO INTERCEPTANDO UMA FORMAÇÃO DE TERRA E '
                                                     'SISTEMA DE PERFILAGEM DE POÇO PARA PERFILAR UM POÇO INTERCEPTANDO UMA FORMAÇÃO DE TERRA'},
                                            {'lang': 'EN',
                                             'text': 'METHOD FOR PERFORMING WELL PROFILETING IN A WELL INTERCEPTING AN EARTH FORMATION AND WELL '
                                                     'PROFILETING SYSTEM FOR PROFILETING A WELL INTERCEPTING AN EARTH FORMATION'}],
                                 'ucid': 'BR-112019002090-B1'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'EP-4266194-A1',
              'number_details': {'titles': [{'lang': 'FR', 'text': "GÉNÉRATION DE MÉTADONNÉES ASSOCIÉES À PLUSIEURS TYPES D'OBJETS"},
                                            {'lang': 'EN', 'text': 'METADATA GENERATION FOR MULTIPLE OBJECT TYPES'},
                                            {'lang': 'DE', 'text': 'METADATENERZEUGUNG FÜR MEHRERE OBJEKTTYPEN'}],
                                 'ucid': 'EP-4266194-A1'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'JP-2021532473-A',
              'number_details': {'titles': [{'lang': 'EN', 'text': 'Storage aggregator controller with metadata arithmetic control'},
                                            {'lang': 'JA', 'text': 'メタデータ演算制御を有するストレージアグリゲータコントローラ'}],
                                 'ucid': 'JP-2021532473-A'},
              'status': 'OK',
              'status_reason': 'success'},
             {'number': 'CN-118333919-A',
              'number_details': {'titles': [{'lang': 'ZH', 'text': '一种用于超声波成像气体泄漏检测仪的图像增强方法'},
                                            {'lang': 'EN', 'text': 'Image enhancement method for ultrasonic imaging gas leakage detector'}],
                                 'ucid': 'CN-118333919-A'},
              'status': 'OK',
              'status_reason': 'success'}]}